// AUTO-GENERATED by scripts/gen-embedded.ts. The committed version is an empty
// stub so typecheck/dev work; `bun run gen:embedded` overwrites it during binary
// builds with real `with { type: "file" }` imports, then it is restored.
export const HAS_EMBEDDED = false;
export const EMBEDDED: Record<string, string> = {};
