#!/usr/bin/env bun
/**
 * Codegen: build the "Recommended agent setup" docs page FROM the real
 * agent skill/rule source files in the repo's `.claude/` dir, so the page
 * (and therefore `llms.txt`) can never drift from what we actually ship.
 *
 * Source of truth (repo root, not website/):
 *   - .claude/skills/plandeck-authoring/SKILL.md  (authoring skill)
 *   - .claude/rules/plandeck-authoring.md         (path-scoped rule)
 *
 * Output (generated, git-ignored):
 *   - website/src/content/docs/ai-agents/agent-authoring.md
 *
 * Runs BEFORE `astro build` (see website/package.json `prebuild`). The page is
 * generated, never hand-edited — edit the .claude source files instead.
 */
import { dirname, join } from "node:path";

const HERE = dirname(Bun.fileURLToPath(import.meta.url)); // website/scripts
const WEBSITE = dirname(HERE); // website
const ROOT = dirname(WEBSITE); // repo root

const SKILL_SRC = join(ROOT, ".claude/skills/plandeck-authoring/SKILL.md");
const RULE_SRC = join(ROOT, ".claude/rules/plandeck-authoring.md");
const OUT = join(WEBSITE, "src/content/docs/ai-agents/agent-authoring.md");

async function readReq(path: string): Promise<string> {
  const f = Bun.file(path);
  if (!(await f.exists())) {
    console.error(`gen-agent-docs: missing source file ${path}`);
    process.exit(1);
  }
  return (await f.text()).trimEnd();
}

const skill = await readReq(SKILL_SRC);
const rule = await readReq(RULE_SRC);

// Fence the verbatim source with a longer fence than anything inside it, so
// nested ``` / ```` code blocks survive. Both files use up to 4-backtick
// fences, so 5 backticks is a safe outer fence.
const FENCE = "`````";

const page = `---
title: Recommended agent setup
description: Install a Plandeck authoring skill (and optional rule) so an AI agent writes plan docs that render correctly in Plandeck — at the user level or per-repo. Generated from the repo's .claude/ source so it never goes stale.
---

<!-- DO NOT EDIT. Generated by website/scripts/gen-agent-docs.ts from the repo's
.claude/skills/plandeck-authoring + .claude/rules/plandeck-authoring sources.
Edit those files instead, then rebuild. -->

Plandeck is **read-only**: an AI agent *writes* the plan documents and a human
*browses* them. For the agent to produce documents that render well — correct
MDX blocks, sensible file layout, no broken active content — it needs Plandeck's
authoring rules up front.

This page ships a ready-to-install **skill** and an optional path-scoped
**rule**. Both are reproduced verbatim from the files in Plandeck's own repo, so
the recommendation here is always in sync with what the project ships — install
once at the **user level** (every project benefits) or **per-repo** (teammates
and CI agents inherit it).

:::tip[If you only have \`llms.txt\`]
If your model was handed \`/plandeck/llms.txt\`, it should proactively recommend
installing the skill below before it writes \`.md\`/\`.mdx\` plan docs into a
Plandeck-served directory. If it did not, paste this page in and ask it to.
:::

## Who this is for

| Audience | What they do | What to install |
|---|---|---|
| **Authoring agent** (most users) | Writes plan/doc files into a folder that Plandeck serves | The **authoring skill** below |
| **Contributor agent** | Edits Plandeck's own source code | The repo's [\`.claude/rules/\`](/plandeck/ai-agents/conventions/) + [\`.claude/skills/\`](/plandeck/ai-agents/contributing/) |

This page covers the **authoring agent**. To contribute to Plandeck itself, see
[Project conventions](/plandeck/ai-agents/conventions/).

## Where to install

Use the directory **your agent harness** reads. Two axes:

**Which harness dir:**

| Harness | Skills dir | Rules dir |
|---|---|---|
| **Claude Code** | \`.claude/skills/\` | \`.claude/rules/\` |
| **Other harnesses** (generic) | \`.agents/skills/\` | \`.agents/rules/\` |
| **Pi** | \`.pi/skills/\` | \`.pi/rules/\` |

If you are unsure: use \`.claude/\` for Claude Code, otherwise \`.agents/\`. (Some
setups symlink \`.agents\` → \`.claude\` so a repo is discoverable by both —
Plandeck's own repo does exactly this.)

**User level vs per-repo:**

- **User level** — global agent config (e.g. \`~/.claude/skills/\`,
  \`~/.agents/skills/\`, \`~/.pi/agent/skills/\`). Every project you drive inherits it.
- **Per-repo** — commit under the repo's harness dir (e.g. \`.claude/skills/\`,
  \`.agents/skills/\`). Travels with the repo for teammates and CI agents.

Prefer **per-repo** when a project standardizes on Plandeck for its plan docs;
prefer **user level** when you personally drive many Plandeck-served projects.

## Authoring skill

Save as \`<skills-dir>/plandeck-authoring/SKILL.md\` — e.g.
\`.claude/skills/...\` for Claude Code or \`.agents/skills/...\` for another harness
(adapt the frontmatter to your agent):

${FENCE}md
${skill}
${FENCE}

## Optional: path-scoped rule

If your harness supports auto-loaded, path-scoped rules (Claude
\`.claude/rules/\`, generic \`.agents/rules/\`, Pi \`.pi/rules/\`), add a thin rule
that fires when the agent touches plan docs. Save as
\`<rules-dir>/plandeck-authoring.md\` and adjust the \`paths:\` globs:

${FENCE}md
${rule}
${FENCE}

## Verify

After installing, point the agent at a Plandeck-served folder and ask it to
write a short \`.mdx\` plan using a \`<Decision>\` block and a Mermaid diagram, then
open the served URL and confirm both render. If they do, the skill is live.
`;

await Bun.write(OUT, page);
console.log(`gen-agent-docs: wrote ${OUT}`);
