#!/usr/bin/env bun
/**
 * Codegen: embed the built SPA (dist/) into the compiled binary.
 *
 * `bun build --compile` only bakes files that are statically imported with
 * `with { type: "file" }`. dist filenames are content-hashed, so we generate a
 * module with one static import per file plus a url-path -> file-path map.
 *
 * Run AFTER `vite build`, BEFORE `bun build --compile`. The generated file
 * overwrites the committed stub at src/server/embedded-assets.ts; the binary
 * build restores the stub afterwards (see package.json build:binary).
 */
import { Glob } from "bun";

const DIST = "dist";
const OUT = "src/server/embedded-assets.ts";

const distFile = Bun.file(`${DIST}/index.html`);
if (!(await distFile.exists())) {
  console.error(`gen-embedded: ${DIST}/index.html not found. Run \`bun run build\` first.`);
  process.exit(1);
}

const glob = new Glob("**/*");
const rels: string[] = [];
for await (const rel of glob.scan({ cwd: DIST, onlyFiles: true })) {
  rels.push(rel.split("\\").join("/"));
}
rels.sort();

if (rels.length === 0) {
  console.error(`gen-embedded: no files under ${DIST}/`);
  process.exit(1);
}

const imports: string[] = [];
const entries: string[] = [];
rels.forEach((rel, i) => {
  imports.push(`import a${i} from "../../dist/${rel}" with { type: "file" };`);
  entries.push(`  ${JSON.stringify(`/${rel}`)}: a${i},`);
});

const body = `// AUTO-GENERATED by scripts/gen-embedded.ts. DO NOT EDIT.
// Regenerated during binary builds; the committed version is an empty stub.
${imports.join("\n")}

export const HAS_EMBEDDED = true;
export const EMBEDDED: Record<string, string> = {
${entries.join("\n")}
};
`;

await Bun.write(OUT, body);
console.log(`gen-embedded: wrote ${OUT} with ${rels.length} embedded files.`);
